### ISSUE TITLE
Request for Location to be turned on only whenever one clicks on my location widget

### ISSUE THREAD

**Issue by githengi** [onaio/kujaku#227]
- [x] Request for Location services to be turned on only whenever one clicks on my location widget

User is being requested to enable Location services  whenever Geowidget is launched instead of when my location widget is clicked

**Comment by ekigamba** [comment]
Sometimes the GPS takes time to get the current user's location, I therefore start getting updates as soon as the user starts using the GeoWidget(warm it) view so that when they click on the button, we just move to their location.

In case this is used with internet, then the response for location would be pretty quick, however for offline situations, this might vary a lot and be disappointing.

I am not sure about your use case, but I guess we can make this configurable so that the host application can control how this happens and document it as usual.

What do you think? @githengi

**Comment by githengi** [comment]
The Geowidget can make when to prompt for location services to be turned on configurable. 

The default can be as is currently.

**Comment by ekigamba** [comment]
Cool 👍

**Comment by githengi** [comment]
This will be implemented in Reveal v2 and Geowidget V3
