### ISSUE TITLE
G3.10 Support drawing arrows between points based on time series information in host application

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#237]
Description from user story ": I want to view the location of all cases in an area, with a visual representation (e.g., arrows, lines) of the relationship between each index case and introduced cases related to each index case."

We need to support the ability to draw arrows on the map from one point to the next showing how a case has moved from point 1 to 2 to 3 to 4, etc. The arrows should be drawn directly as lines, not following any types of path or road.

Use Case:
- A user moves from house to house testing each member for malaria.
- If the malaria test is positive, they provide treatment immediately and each test is recorded in the host application.
- Forms are submitted at every house as the user moves through the village and each form contains time series information (formSubmission datetime).
- The user wants to view the location of all cases in the area displayed on the GeoWidget so they can see how they moved throughout the village and all of the positive cases.

Development Required:
The sample app will need to have a push button that toggles drawing arrows between 5 points based on some "dateTime" property that's passed in from the host application. The arrows should identify which points have the earliest dateTime, order them earliest to latest and then draw an arrow from structure to structure. At this moment, the sample app does not need bounding box support, just work on sample data.

- [x] Define an appropriate dateTime property and testStatus property (positive, negative, not-tested) that we want to track on each structure "passed in by the host application"
- [x] Create 10 points of demo data with the dateTime property. Six are blue representing cases found  (testStatus = positive) and four are purple representing visited but no cases found (testStatus = negative).
- [x] Add the business logic that does the calculations (1. Find all points that have the dateTime property on the screen; 2. Within those, find all the points that have the testStatus = positive; 3. Order the points;
- [x] Add a button to the GeoWidget that draws the arrows. No animation is needed, we just need arrows to show up on the map

**Comment by ekigamba** [comment]
![screen shot 2019-02-05 at 6 08 49 pm](https://user-images.githubusercontent.com/31766075/52284415-65f55480-2975-11e9-84f1-a501f0a5efb3.png)

The arrows can probably be like above. Taken from the Mapbox navigation site


**DRAFT OF THE FEATURE SUPPORTING DRAWING ARROWS**

- Arrow-line color + stroke + shadow(if any) should be configurable
- The arrows should be drawn passing below the structures
- At least or probably just one arrow between two edges
- One of the parameters can be the list of GeoJSON for which to draw the vertices(arrows in this case) . The host application can use the query API to fetch features from the style
- The Expressions query provided by Mapbox is enough for making the feature selection(query)  and case relationship dynamic enough
- Another option of the parameters could also be to pass expressions and/or layer-ids so as to make the case relationship dynamic enough
- Arrows should be draw below the structures
- Only one arrow between two edges(cases)
- The sort field & sort order should be configurable
  - String and numbers should work OK natively
  - We should add support for **DATE** in case of string formatted dates which should work the the provided string to date conversion native functions
  - Provision of sorting interface so that this is also easily changeable to the host preference

**Assumptions**

- The arrow color might change depending on theme or case relationship being displayed
- The arrow direction might be different depending for different use-cases
- The cases might be on different layers
- The cases(features) might need to match different conditions - This will be easy **IF** the [Mapbox Expressions](https://docs.mapbox.com/android/maps/overview/expressions/) can work to fit the query requirements since it's already used in querying features on the Mapbox map

@githengi @craigappl

**Comment by craigappl** [comment]
@Kigamba this looks great. I have a couple more notes:
- We will need to support 'n' points as we draw this. The index case is the first, then, based on the time series, we will have to draw the lines point to point until the investigation is complete. So, this feature will need to demonstrate drawing lines from the first structure to 5 structures
- This will need to support drawing lines from any point, polygon or multi-polygon.
- We definitely need to sort by datetime.

**Comment by ekigamba** [comment]
@craigappl 

> * We will need to support 'n' points as we draw this. The index case is the first, then, based on the time series, we will have to draw the lines point to point until the investigation is complete. So, this feature will need to demonstrate drawing lines from the first structure to 5 structures

Definitely, forgot to explicitly state that.

> * This will need to support drawing lines from any point, polygon or multi-polygon.

I will add this also to the current draft

> * We definitely need to sort by datetime.

Cool, this will be high priority

**Comment by ekigamba** [comment]
It seems like the feature querying provided by Mapbox will not work for our feature selection
The current `MapboxMap.queryRenderedFeatures` method only works for rendered features.
The current `VectorSource/GeoJsonSource.querySourceFeatures` methods  have the following limits:
- According to Mapbox documentation [here](https://docs.mapbox.com/android/maps/overview/query/#query-source-features), it cannot retrieve features outside the current viewport "`The domain of the query includes all currently-loaded vector tiles and GeoJSON source tiles: this function does not check tiles outside the currently visible viewport`"
- Do not work either across sources or across layers uniformly. For each to work, we would need to define different params around each and specific conditions for each which do not seem to achieve our goals easily or out of our scope provided. From the scope, the host application will be assumed to always have a `list of features` from which the selection will be made


We currently only need a dynamic enough feature selection feature so that the feature selection can work dynamically for the few use-cases


## TERMS

**Feature selection** - This is definition of conditions for which features should meet to be selected for case relationship

**Comment by githengi** [comment]
I think the host application should be able to pass the property that has `date time` to the GeoWidget. 

The host app should also pass the property that has `status`, also the `status states` when arrows should be drawn.

The host app should also send the `GeoJSON` of the points.

The Geowidget with the above data should be able to 

1. Filter points that have a status that should be drawn
2. Filter points from 1 above that have date time property
3. Sort the points from 2 above
4. Draw the arrows from the earliest one to the last one

**Comment by ekigamba** [comment]
Cool, so for filtering of points. Do we only make equalTo filtering for a single string property on the GeoWidget?

**Comment by githengi** [comment]
@craigappl please reply to this. 

`equalTo` should be mandatory and probably filtering via regex should also be supported.

**Comment by craigappl** [comment]
@githengi and @Kigamba , are these really two separate features that should be split out?

Feature 1) Allow for filtering of points on the GeoWidget (https://github.com/onaio/kujaku/issues/259)
Feature 2) Draw lines between the filtered points

They may not need to be separate features in the UI, but I would recommend considering different methods that can be used by the host application.

**Comment by githengi** [comment]
@craigappl  @Kigamba 

The features should be split. Filtering should be different from drawing lines between points.

The filtering can be by any of the feature(business data) properties. A builder pattern can be used to chain multiple filters using different properties e.g `type = residential` and `tesstatus =  positive`

Drawing the arrows will use the filtering feature to filter and draw the arrows for only the valid structures.
